Footer
Ynln69/parcel-project-5 pull request #37
Opened 2022-12-02 21:50 UTC by yarikgorpl

Повиправляв синтаксичні помилки в шляхах посиланнь

2022-12-02 23:14 UTC, Ynln69 requested changes

2022-12-02 23:14 UTC, Ynln69 commented on src/partials/header-footer/footer.html
> +        <li class="footer-nav__item"><a class="footer-nav__link" href="/src/page-hotel.html">Готель</a></li>
тут не потрібно вказувати src , має бути просто кнопочка

2022-12-02 23:14 UTC, Ynln69 commented on src/sass/header-footer/_footer.scss
> +  font-family: FilmP3;
підключення шрифтів 
font-family: font(_film_) 
заміни код

2022-12-03 03:06 UTC, MStartsev commented on src/sass/header-footer/_footer.scss
> +  font-family: FilmP3;
font-family: font(_film_)

!!! не забувайте за знак підкреслення плз)    _film_   ,   _times_    ,   _montserrat
підказки в _fonts.scss

2022-12-03 10:10 UTC, merged